[package]
name = "pq-query"
version.workspace = true
edition.workspace = true

[dependencies]
pq-core.workspace = true
arrow.workspace = true
parquet.workspace = true
datafusion.workspace = true
jaq-interpret.workspace = true
jaq-core.workspace = true
jaq-std.workspace = true
jaq-parse.workspace = true
serde_json.workspace = true
thiserror.workspace = true
tokio.workspace = true
