[package]
name = "pq-core"
version.workspace = true
edition.workspace = true

[dependencies]
arrow.workspace = true
parquet.workspace = true
object_store.workspace = true
url.workspace = true
futures.workspace = true
tokio.workspace = true
serde.workspace = true
serde_json.workspace = true
thiserror.workspace = true
bytesize.workspace = true
chrono.workspace = true
async-trait.workspace = true
